database: mysql

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:{DB_PORT}/${DB_NAME}?cloudSqlInstance=${INSTANCE_CONNECTION_NAME}&user=${DB_USER}&password=${DB_PASS}&useSSL=false&allowPublicKeyRetrieval=true&useUnicode=yes&characterEncoding=UTF-8&connectTimeout=5
    username: ${DB_USER}
    password: ${DB_PASS}
    properties:
      hibernate:
        format_sql: true
  cloud:
    gcp:
      sql:
        enabled: false
        database-name: ${DB_NAME}
        instance-connection-name: ${INSTANCE_CONNECTION_NAME}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  sql:
    init:
      mode:
        always

  security:
    oauth2:
      client:
        registration:
          authProvider:
            client-id: shilpa
            client-secret: shilpa@sh
            authorization-grant-type: password
        provider:
          authProvider:
            #token-uri: http://34.133.128.223:80/oauth/token
            token-uri: http://authorizationserver-app.default.svc.cluster.local/oauth/token
      resource:
        server:
          #url: http://34.28.252.10:80/users
          url: http://resourceserver-app.default.svc.cluster.local/users

server:
  port: 8083


