kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: registration-external
  labels:
    gateway: external-http
spec:
  parentRefs:
    - name: external-http
  hostnames:
    - "registration.example.com"
  rules:
    - backendRefs:
        - name: registration-v1
          port: 8080